# permissions for end users to edit imagepullsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecret-editor-role
rules:
- apiGroups:
  - example.apstn.dev
  resources:
  - imagepullsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.apstn.dev
  resources:
  - imagepullsecrets/status
  verbs:
  - get
